"""Resolve shared database path."""

from __future__ import annotations

from pathlib import Path

from .runtime import MCP_DIR


def resolve_expense_db_path() -> Path:
    import sys

    sys.path.insert(0, str(MCP_DIR))
    from expense_tracker.paths import resolve_db_path

    return resolve_db_path()


def save_household_db_path(path: Path) -> None:
    import sys

    sys.path.insert(0, str(MCP_DIR))
    from expense_tracker.paths import db_path_override_file, expense_tracker_dir

    expense_tracker_dir().mkdir(parents=True, exist_ok=True)
    db_path_override_file().write_text(f"{path}\n", encoding="utf-8")


def write_env_paths(db_path: Path) -> None:
    from .runtime import ENV_PATHS_FILE, MCP_DIR, env_path_value, venv_python

    py = venv_python()
    ENV_PATHS_FILE.write_text(
        "\n".join(
            [
                "# Generated by bootstrap — append to each profile .env",
                f"EXPENSE_MCP_PYTHON={env_path_value(py)}",
                f"EXPENSE_MCP_SERVER_PATH={env_path_value(MCP_DIR / 'server.py')}",
                f"EXPENSE_DB_PATH={env_path_value(db_path)}",
                "",
            ]
        ),
        encoding="utf-8",
    )
